version: "3"
services:
  ech0:
    image: sn0wl1n/ech0:latest
    container_name: ech0
    ports:
      - "6277:6277"
      - "6278:6278"
    volumes:
      - ./ech0/data:/app/data
      - /proc:/host_proc:ro
      - /sys/fs/cgroup:/host_cgroup:ro
    environment:
      - JWT_SECRET=Hello Echos
      - HOST_PROC=/host_proc
      - HOST_CGROUP=/host_cgroup
