{{- if .Values.config.JWT_SECRET -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ech0.fullname" . }}
  labels:
    {{- include "ech0.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.config.JWT_SECRET | b64enc | quote }}
{{- end -}}
